//! Canonical example config and JSON Schema, generated from the config types so
//! they can't drift from what the application actually parses.
//! Regenerate the committed files with `cargo run --bin gen_config -- --write`.

use std::path::PathBuf;

use crate::config::cache::CacheConfig;
use crate::config::application::{
    ApplicationConfig, DisplayConfig, DisplayKind, FileStoreConfig, LocationConfig, StaleDataConfig,
};
use crate::config::departures::{
    DepartureBoardConfig, DepartureSource, OpenLdbwsConfig, ProvidersConfig, TflConfig,
    DEFAULT_TFL_HOST_URL,
};
use crate::config::server::ServerConfig;
use crate::domain::models::display::{Dither, ImageFormat};
use crate::config::weather::{OpenWeatherConfig, WeatherConfig, WeatherProvider};

/// Header so editors with TOML schema support (taplo / "Even Better TOML")
/// give completion, hover docs and validation.
const EXAMPLE_HEADER: &str = "#:schema ./schema.json\n\
    # Generated by `cargo run --bin gen_config -- --write`; edit src/config/example.rs instead.\n\n";

impl ApplicationConfig {
    pub fn example() -> Self {
        let board = |name: &str, travel_minutes, source| DepartureBoardConfig {
            name: name.to_owned(),
            enabled: true,
            rows: 4,
            travel_minutes,
            source,
        };
        ApplicationConfig {
            weather: WeatherConfig {
                enabled: true,
                provider: WeatherProvider::OpenWeather,
                open_weather: Some(OpenWeatherConfig {
                    api_key: "0".repeat(32),
                    host_url: "https://api.openweathermap.org".to_owned(),
                }),
                open_meteo: None,
            },
            departures: vec![
                board(
                    "NORTHBOUND",
                    5,
                    DepartureSource::OpenLdbws { from: "HRN".into(), to: "WIH".into() },
                ),
                board(
                    "SOUTHBOUND",
                    5,
                    DepartureSource::OpenLdbws { from: "HRN".into(), to: "FPK".into() },
                ),
                board("TURNPIKE LANE", 15, DepartureSource::Tfl { stop_id: "940GZZLUTPN".into() }),
            ],
            providers: ProvidersConfig {
                open_ldbws: Some(OpenLdbwsConfig {
                    api_key: "your-raildata-consumer-key".to_owned(),
                    host_url: "https://api1.raildata.org.uk/1010-live-arrival-and-departure-boards-arr-and-dep1_1/LDBWS/api/20220120/GetArrDepBoardWithDetails".to_owned(),
                }),
                tfl: Some(TflConfig {
                    app_key: Some("your-tfl-app-key".to_owned()),
                    host_url: DEFAULT_TFL_HOST_URL.to_owned(),
                }),
            },
            location: LocationConfig { latitude: 51.5, longitude: -0.12 },
            file_store: FileStoreConfig { save_directory: PathBuf::from("./output") },
            cache: CacheConfig { directory: PathBuf::from("./cache") },
            display: DisplayConfig {
                kind: DisplayKind::WaveshareEpd7in5V2,
                dither: Dither::None,
                image_format: ImageFormat::Bmp,
            },
            stale_data: StaleDataConfig::default(),
            server: ServerConfig::default(),
        }
    }

    pub fn example_toml() -> String {
        let body = toml::to_string_pretty(&Self::example()).expect("example config serializes");
        format!("{EXAMPLE_HEADER}{body}")
    }

    pub fn json_schema() -> String {
        let schema = schemars::schema_for!(ApplicationConfig);
        serde_json::to_string_pretty(&schema).expect("schema serializes") + "\n"
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use serde_valid::Validate;

    use super::*;

    #[test]
    fn example_loads_and_validates_through_the_real_loader() {
        let path = std::env::temp_dir().join("eink_example_config_test.toml");
        std::fs::write(&path, ApplicationConfig::example_toml()).unwrap();
        let config = ApplicationConfig::new(&path).expect("example parses");
        config.validate().expect("example is valid");
        assert_eq!(config.departures.len(), 3);
    }

    #[test]
    fn committed_files_are_up_to_date() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("config");
        let hint = "run `cargo run --bin gen_config -- --write`";
        assert_eq!(
            std::fs::read_to_string(dir.join("example.toml")).unwrap_or_default(),
            ApplicationConfig::example_toml(),
            "config/example.toml is stale: {hint}"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("schema.json")).unwrap_or_default(),
            ApplicationConfig::json_schema(),
            "config/schema.json is stale: {hint}"
        );
    }
}
